### ISSUE TITLE
Release 2.5 doesn't work on OSX 10.8

### ISSUE THREAD

**Issue by taisel** [mupen64plus/mupen64plus-core#151]
Error "dyld: Symbol not found: ___strlcpy_chk" from within SDL2 lib used. A quick Google search of the exact text reveals command line git has the same issue, and reveals it's because they're being compiled for Mavericks and up now (10.9). I switch between OSX versions on my HDD for various reasons and noticed mupen64plus doesn't like Mountain Lion.

The reason this is an issue is because the readme says it works on 10.8 and maybe 10.7.

**Comment by taisel** [comment]
Yeah runs fine out of the box on El Capitan though.

**Comment by rlabrecque** [comment]
Which readme says this?

**Comment by taisel** [comment]
The one inside https://github.com/mupen64plus/mupen64plus-core/releases/download/2.5/mupen64plus-bundle-osx64-2.5.zip

**Comment by richard42** [comment]
Thanks for bringing this to our attention.  I have updated the script which
generates this Readme.txt file to reflect the fact that we now required OSX
10.9 or later.

Richard
