### ISSUE TITLE
fails to build since 5aebce38204de4fe3671f78e3cee66838f9a1d87

### ISSUE THREAD

**Issue by charlemagnelasse** [mupen64plus/mupen64plus-core#230]
The build fails since 5aebce38204de4fe3671f78e3cee66838f9a1d87

     ../../src/main/rom.c: In function 'romdatabase_open':
     ../../src/main/rom.c:449:38: error: 'DEFAULT' undeclared (first use in this function)
                  search->entry.savetype = DEFAULT;

See https://travis-ci.org/mupen64plus/mupen64plus-core/builds/197207056

**Comment by charlemagnelasse** [comment]
@bsmiles32 please have a look

**Comment by bsmiles32** [comment]
This is due to some merging oops in commit  beb8ad3. See my comment there

**Comment by richard42** [comment]
this should be fixed now.
